export const PELICULAS_RECEIVED = 'PELICULAS_RECEIVED';
export const CATEGORIAS_RECEIVED = 'CATEGORIAS_RECEIVED';
export const PROTAGONISTAS_RECEIVED = "PROTAGONISTAS_RECEIVED";
export const DIRECTORES_RECEIVED = 'DIRECTORES_RECEIVED';