export const PELICULAS_RECEIVED = 'PELICULAS_RECEIVED';
export const SEARCH_PELICULAS = 'SEARCH_PELICULAS';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_PELICULA = 'SET_PELICULA';
export const SET_NOMBRE_PELICULA = 'SET_NOMBRE_PELICULA';
export const SET_DIRECTOR_PELICULA = 'SET_DIRECTOR_PELICULA';
export const SET_CATEGORIA_PELICULA = 'SET_CATEGORIA_PELICULA';
export const SET_PROTAGONISTAS_PELICULA = 'SET_PROTAGONISTAS_PELICULA';
export const SET_DURACION_PELICULA = 'SET_DURACION_PELICULA';
//Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_CONFIRM = 'SET_CONFIRM';
export const MODAL_COMPONENT = 'MODAL_COMPONENT';
